name: Run markdownlint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown Lint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: "."
          config_file: ".markdownlint.yml"
      - name: Yaml Lint
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_strict: true
          yamllint_config_filepath: ".yamllint"
